"use client"

import { useState } from "react"
import { motion, AnimatePresence } from "framer-motion"
import { Calendar, RefreshCw, Send, Download } from "lucide-react"
import { cn } from "@/lib/utils"
import { ActivityChart } from "@/components/gitdigest/activity-chart"
import { SummaryPanel } from "@/components/gitdigest/summary-panel"
import {
  GeneratingLoader,
  EmptyState,
  ChartSkeleton,
} from "@/components/gitdigest/loading-states"
import type { DigestReport } from "@/lib/gitdigest/ai"

const DATE_RANGES = [
  { label: "7 days", value: 7 },
  { label: "14 days", value: 14 },
  { label: "30 days", value: 30 },
]

export default function GitDigestDashboard() {
  const [selectedRange, setSelectedRange] = useState(7)
  const [isLoading, setIsLoading] = useState(false)
  const [report, setReport] = useState<DigestReport | null>(null)
  const [error, setError] = useState<string | null>(null)

  const generateReport = async () => {
    setIsLoading(true)
    setError(null)

    try {
      const res = await fetch("/api/gitdigest/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ daysBack: selectedRange }),
      })

      const data = await res.json()

      if (!data.success) {
        throw new Error(data.error || "Failed to generate report")
      }

      if (!data.report) {
        setError(data.message || "No activity found")
        setReport(null)
      } else {
        setReport(data.report)
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : "Something went wrong")
    } finally {
      setIsLoading(false)
    }
  }

  const downloadReport = () => {
    if (!report) return

    // Create markdown content
    const startDate = new Date(report.dateRange.start).toLocaleDateString()
    const endDate = new Date(report.dateRange.end).toLocaleDateString()

    let md = `# Dev Report\n## ${startDate} - ${endDate}\n\n`
    md += `### Executive Summary\n`
    report.executiveSummary.forEach((item) => {
      md += `- ${item}\n`
    })
    md += `\n### Stats\n`
    md += `- Total Commits: ${report.stats.totalCommits}\n`
    md += `- Active Repos: ${report.stats.activeRepos}\n`
    md += `- Peak Day: ${report.stats.mostActiveDayCommits} commits\n\n`
    md += `### Detailed Breakdown\n`
    report.detailedBreakdown.forEach((breakdown) => {
      md += `\n**${breakdown.repo}** (${breakdown.commitCount} commits)\n`
      md += `${breakdown.summary}\n`
      breakdown.highlights.forEach((h) => {
        md += `- ${h}\n`
      })
    })
    md += `\n---\n*Generated by GitDigest*\n`

    const blob = new Blob([md], { type: "text/markdown" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = `dev-report-${new Date().toISOString().split("T")[0]}.md`
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="space-y-8">
      {/* Hero Section */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="space-y-4"
      >
        <h1 className="text-3xl font-bold tracking-tight md:text-4xl">
          GitDigest
        </h1>
        <p className="max-w-2xl text-muted-foreground">
          Your GitHub activity, translated for humans. Generate PM-ready reports
          that summarize what you&apos;ve been working on.
        </p>
      </motion.div>

      {/* Controls */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.1 }}
        className="flex flex-wrap items-center gap-4"
      >
        {/* Date range selector */}
        <div className="flex items-center gap-2 rounded-lg border border-border bg-card p-1">
          <Calendar className="ml-2 h-4 w-4 text-muted-foreground" />
          {DATE_RANGES.map((range) => (
            <button
              key={range.value}
              onClick={() => setSelectedRange(range.value)}
              className={cn(
                "rounded-md px-3 py-1.5 text-sm font-medium transition-colors",
                selectedRange === range.value
                  ? "bg-primary text-primary-foreground"
                  : "text-muted-foreground hover:text-foreground"
              )}
            >
              {range.label}
            </button>
          ))}
        </div>

        {/* Generate button */}
        <motion.button
          onClick={generateReport}
          disabled={isLoading}
          whileHover={{ scale: 1.02 }}
          whileTap={{ scale: 0.98 }}
          className={cn(
            "flex items-center gap-2 rounded-lg bg-accent px-4 py-2 font-medium text-white",
            "transition-opacity hover:opacity-90",
            "disabled:cursor-not-allowed disabled:opacity-50"
          )}
        >
          <RefreshCw className={cn("h-4 w-4", isLoading && "animate-spin")} />
          {isLoading ? "Generating..." : "Generate Report"}
        </motion.button>

        {/* Action buttons (show when report exists) */}
        <AnimatePresence>
          {report && !isLoading && (
            <motion.div
              initial={{ opacity: 0, x: -10 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: -10 }}
              className="flex gap-2"
            >
              <button
                onClick={downloadReport}
                className="flex items-center gap-2 rounded-lg border border-border px-3 py-2 text-sm transition-colors hover:bg-muted"
              >
                <Download className="h-4 w-4" />
                Download
              </button>
              <button
                className="flex items-center gap-2 rounded-lg border border-border px-3 py-2 text-sm transition-colors hover:bg-muted"
                title="Email report (coming soon)"
              >
                <Send className="h-4 w-4" />
                Email
              </button>
            </motion.div>
          )}
        </AnimatePresence>
      </motion.div>

      {/* Main Content */}
      <div className="grid gap-8 lg:grid-cols-3">
        {/* Left column - Chart */}
        <div className="lg:col-span-1">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.2 }}
            className="rounded-xl border border-border/50 bg-card/30 p-6"
          >
            <h2 className="mb-4 text-lg font-semibold">Activity</h2>
            {isLoading ? (
              <ChartSkeleton />
            ) : report ? (
              <ActivityChart data={report.stats.commitsByDay} />
            ) : (
              <div className="flex h-[200px] items-center justify-center text-sm text-muted-foreground">
                Generate a report to see activity
              </div>
            )}
          </motion.div>
        </div>

        {/* Right column - Report */}
        <div className="lg:col-span-2">
          <AnimatePresence mode="wait">
            {isLoading ? (
              <motion.div
                key="loading"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
              >
                <GeneratingLoader />
              </motion.div>
            ) : error ? (
              <motion.div
                key="error"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
              >
                <EmptyState
                  title="No activity found"
                  description={error}
                  action={
                    <button
                      onClick={generateReport}
                      className="rounded-lg bg-accent px-4 py-2 text-sm font-medium text-white hover:opacity-90"
                    >
                      Try Again
                    </button>
                  }
                />
              </motion.div>
            ) : report ? (
              <motion.div
                key="report"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
              >
                <SummaryPanel report={report} />
              </motion.div>
            ) : (
              <motion.div
                key="empty"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
              >
                <EmptyState
                  title="No report yet"
                  description="Select a date range and click 'Generate Report' to create your first dev summary."
                  action={
                    <button
                      onClick={generateReport}
                      className="rounded-lg bg-accent px-4 py-2 text-sm font-medium text-white hover:opacity-90"
                    >
                      Generate Report
                    </button>
                  }
                />
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      </div>
    </div>
  )
}
