import { Resend } from "resend"
import type { DigestReport } from "./ai"

function getResendClient() {
  const apiKey = process.env.RESEND_API_KEY
  if (!apiKey) {
    throw new Error("RESEND_API_KEY environment variable is not set")
  }
  return new Resend(apiKey)
}

export interface EmailOptions {
  to: string
  subject?: string
}

export async function sendReportEmail(
  report: DigestReport,
  username: string,
  options: EmailOptions
) {
  const startDate = new Date(report.dateRange.start).toLocaleDateString(
    "en-US",
    { month: "short", day: "numeric" }
  )
  const endDate = new Date(report.dateRange.end).toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  })

  const subject =
    options.subject || `Dev Report: ${username} (${startDate} - ${endDate})`

  const html = generateEmailHtml(report, username, startDate, endDate)

  const resend = getResendClient()
  const { data, error } = await resend.emails.send({
    from: "GitDigest <gitdigest@tylerschmidt.dev>",
    to: options.to,
    subject,
    html,
  })

  if (error) {
    throw new Error(`Failed to send email: ${error.message}`)
  }

  return data
}

function generateEmailHtml(
  report: DigestReport,
  username: string,
  startDate: string,
  endDate: string
): string {
  const bulletPoints = report.executiveSummary
    .map((item) => `<li style="margin-bottom: 8px;">${item}</li>`)
    .join("")

  const repoBreakdowns = report.detailedBreakdown
    .map(
      (breakdown) => `
      <div style="margin-bottom: 20px; padding: 16px; background: #f8f9fa; border-radius: 8px;">
        <h3 style="margin: 0 0 8px 0; font-size: 16px;">
          <a href="${breakdown.repoUrl}" style="color: #2563eb; text-decoration: none;">
            ${breakdown.repo}
          </a>
          <span style="color: #6b7280; font-weight: normal;"> (${breakdown.commitCount} commits)</span>
        </h3>
        <p style="margin: 0 0 12px 0; color: #4b5563;">${breakdown.summary}</p>
        ${
          breakdown.highlights.length > 0
            ? `<ul style="margin: 0; padding-left: 20px; color: #374151;">
            ${breakdown.highlights.map((h) => `<li style="margin-bottom: 4px;">${h}</li>`).join("")}
          </ul>`
            : ""
        }
      </div>
    `
    )
    .join("")

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Dev Report</title>
</head>
<body style="margin: 0; padding: 0; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; background-color: #f3f4f6;">
  <div style="max-width: 600px; margin: 0 auto; padding: 40px 20px;">
    <!-- Header -->
    <div style="background: linear-gradient(135deg, #1e40af 0%, #3b82f6 100%); border-radius: 12px 12px 0 0; padding: 32px; text-align: center;">
      <h1 style="margin: 0; color: white; font-size: 24px; font-weight: bold;">Dev Report</h1>
      <p style="margin: 8px 0 0 0; color: rgba(255,255,255,0.9); font-size: 14px;">${username} • ${startDate} - ${endDate}</p>
    </div>

    <!-- Main Content -->
    <div style="background: white; padding: 32px; border-radius: 0 0 12px 12px; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.1);">

      <!-- Stats -->
      <div style="display: flex; justify-content: space-around; margin-bottom: 32px; text-align: center;">
        <div>
          <div style="font-size: 32px; font-weight: bold; color: #2563eb;">${report.stats.totalCommits}</div>
          <div style="font-size: 12px; color: #6b7280; text-transform: uppercase;">Commits</div>
        </div>
        <div>
          <div style="font-size: 32px; font-weight: bold; color: #1f2937;">${report.stats.activeRepos}</div>
          <div style="font-size: 12px; color: #6b7280; text-transform: uppercase;">Repos</div>
        </div>
        <div>
          <div style="font-size: 32px; font-weight: bold; color: #059669;">${report.stats.mostActiveDayCommits}</div>
          <div style="font-size: 12px; color: #6b7280; text-transform: uppercase;">Peak Day</div>
        </div>
      </div>

      <!-- Executive Summary -->
      <div style="margin-bottom: 32px;">
        <h2 style="margin: 0 0 16px 0; font-size: 18px; color: #1f2937;">Executive Summary</h2>
        <ul style="margin: 0; padding-left: 20px; color: #374151; line-height: 1.6;">
          ${bulletPoints}
        </ul>
      </div>

      <!-- Detailed Breakdown -->
      <div>
        <h2 style="margin: 0 0 16px 0; font-size: 18px; color: #1f2937;">Detailed Breakdown</h2>
        ${repoBreakdowns}
      </div>
    </div>

    <!-- Footer -->
    <div style="text-align: center; padding: 24px; color: #6b7280; font-size: 12px;">
      <p style="margin: 0;">Generated by <a href="https://tylerschmidt.dev/gitdigest" style="color: #2563eb;">GitDigest</a></p>
    </div>
  </div>
</body>
</html>
  `
}
