"use client"

import { useState, useEffect, useCallback } from "react"
import { motion, AnimatePresence } from "framer-motion"
import { Calendar, RefreshCw, Download } from "lucide-react"
import { cn } from "@/lib/utils"
import { ActivityChart } from "@/components/gitdigest/activity-chart"
import {
  GeneratingLoader,
  EmptyState,
  ChartSkeleton,
} from "@/components/gitdigest/loading-states"
import type { DigestReport } from "@/lib/gitdigest/ai"

const DATE_RANGES = [
  { label: "7 days", value: 7 },
  { label: "14 days", value: 14 },
  { label: "30 days", value: 30 },
]

export default function GitDigestDashboard() {
  const [selectedRange, setSelectedRange] = useState(7)
  const [isLoading, setIsLoading] = useState(true)
  const [report, setReport] = useState<DigestReport | null>(null)
  const [error, setError] = useState<string | null>(null)

  const fetchReport = useCallback(async (daysBack: number) => {
    setIsLoading(true)
    setError(null)

    try {
      const res = await fetch("/api/gitdigest/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ daysBack }),
      })

      const data = await res.json()

      if (!data.success) {
        throw new Error(data.error || "Failed to generate report")
      }

      if (!data.report) {
        setError(data.message || "No activity found")
        setReport(null)
      } else {
        setReport(data.report)
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : "Something went wrong")
    } finally {
      setIsLoading(false)
    }
  }, [])

  // Auto-fetch on mount and when date range changes
  useEffect(() => {
    fetchReport(selectedRange)
  }, [selectedRange, fetchReport])

  const handleRangeChange = (value: number) => {
    if (value !== selectedRange) {
      setSelectedRange(value)
    }
  }

  const downloadReport = () => {
    if (!report) return

    const startDate = new Date(report.dateRange.start).toLocaleDateString()
    const endDate = new Date(report.dateRange.end).toLocaleDateString()

    let md = `# Dev Report\n## ${startDate} - ${endDate}\n\n`
    md += `### Executive Summary\n`
    report.executiveSummary.forEach((item) => {
      md += `- ${item}\n`
    })
    md += `\n### Stats\n`
    md += `- Total Commits: ${report.stats.totalCommits}\n`
    md += `- Active Repos: ${report.stats.activeRepos}\n`
    md += `- Peak Day: ${report.stats.mostActiveDayCommits} commits\n\n`
    md += `### Detailed Breakdown\n`
    report.detailedBreakdown.forEach((breakdown) => {
      md += `\n**${breakdown.repo}** (${breakdown.commitCount} commits)\n`
      md += `${breakdown.summary}\n`
      breakdown.highlights.forEach((h) => {
        md += `- ${h}\n`
      })
    })
    md += `\n---\n*Generated by GitDigest*\n`

    const blob = new Blob([md], { type: "text/markdown" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = `dev-report-${new Date().toISOString().split("T")[0]}.md`
    a.click()
    URL.revokeObjectURL(url)
  }

  const formatDateRange = () => {
    if (!report) return ""
    const start = new Date(report.dateRange.start).toLocaleDateString("en-US", {
      month: "short",
      day: "numeric",
    })
    const end = new Date(report.dateRange.end).toLocaleDateString("en-US", {
      month: "short",
      day: "numeric",
      year: "numeric",
    })
    return `${start} – ${end}`
  }

  return (
    <div className="space-y-8">
      {/* Header with controls */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"
      >
        <div>
          <h1 className="text-3xl font-bold tracking-tight md:text-4xl">
            Activity Summary
          </h1>
          <p className="mt-1 text-muted-foreground">
            {report ? formatDateRange() : "Loading..."}
          </p>
        </div>

        <div className="flex flex-wrap items-center gap-3">
          {/* Date range selector */}
          <div className="flex items-center gap-2 rounded-lg border border-border bg-card p-1">
            <Calendar className="ml-2 h-4 w-4 text-muted-foreground" />
            {DATE_RANGES.map((range) => (
              <button
                key={range.value}
                onClick={() => handleRangeChange(range.value)}
                disabled={isLoading}
                className={cn(
                  "rounded-md px-3 py-1.5 text-sm font-medium transition-colors",
                  selectedRange === range.value
                    ? "bg-primary text-primary-foreground"
                    : "text-muted-foreground hover:text-foreground",
                  isLoading && "cursor-not-allowed opacity-50"
                )}
              >
                {range.label}
              </button>
            ))}
          </div>

          {/* Refresh button */}
          <button
            onClick={() => fetchReport(selectedRange)}
            disabled={isLoading}
            className={cn(
              "flex items-center gap-2 rounded-lg border border-border px-3 py-2 text-sm transition-colors hover:bg-muted",
              isLoading && "cursor-not-allowed opacity-50"
            )}
          >
            <RefreshCw className={cn("h-4 w-4", isLoading && "animate-spin")} />
            Refresh
          </button>

          {/* Download button */}
          {report && !isLoading && (
            <button
              onClick={downloadReport}
              className="flex items-center gap-2 rounded-lg border border-border px-3 py-2 text-sm transition-colors hover:bg-muted"
            >
              <Download className="h-4 w-4" />
              Export
            </button>
          )}
        </div>
      </motion.div>

      {/* Loading state */}
      <AnimatePresence mode="wait">
        {isLoading ? (
          <motion.div
            key="loading"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="space-y-8"
          >
            <GeneratingLoader />
            <div className="rounded-xl border border-border/50 bg-card/30 p-6">
              <ChartSkeleton />
            </div>
          </motion.div>
        ) : error ? (
          <motion.div
            key="error"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
          >
            <EmptyState
              title="Unable to load activity"
              description={error}
              action={
                <button
                  onClick={() => fetchReport(selectedRange)}
                  className="rounded-lg bg-accent px-4 py-2 text-sm font-medium text-white hover:opacity-90"
                >
                  Try Again
                </button>
              }
            />
          </motion.div>
        ) : report ? (
          <motion.div
            key="report"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="space-y-8"
          >
            {/* Executive Summary - prominent at top */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              className="rounded-xl border border-accent/20 bg-gradient-to-br from-accent/5 to-transparent p-6"
            >
              <div className="mb-4 flex items-center gap-3">
                <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-accent text-white">
                  <svg
                    className="h-5 w-5"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                    strokeWidth={2}
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z"
                    />
                  </svg>
                </div>
                <h2 className="text-xl font-semibold">Executive Summary</h2>
              </div>
              <ul className="space-y-3">
                {report.executiveSummary.map((item, i) => (
                  <motion.li
                    key={i}
                    initial={{ opacity: 0, x: -10 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ delay: i * 0.1 }}
                    className="flex gap-3 text-sm leading-relaxed"
                  >
                    <span className="mt-1 h-1.5 w-1.5 shrink-0 rounded-full bg-accent" />
                    <span>{item}</span>
                  </motion.li>
                ))}
              </ul>
            </motion.div>

            {/* Stats row */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.1 }}
              className="grid grid-cols-3 gap-4"
            >
              <div className="rounded-xl border border-border/50 bg-card/50 p-4 text-center">
                <p className="text-3xl font-bold text-accent">
                  {report.stats.totalCommits}
                </p>
                <p className="text-xs text-muted-foreground">Total Commits</p>
              </div>
              <div className="rounded-xl border border-border/50 bg-card/50 p-4 text-center">
                <p className="text-3xl font-bold">{report.stats.activeRepos}</p>
                <p className="text-xs text-muted-foreground">Active Repos</p>
              </div>
              <div className="rounded-xl border border-border/50 bg-card/50 p-4 text-center">
                <p className="text-3xl font-bold text-green-500">
                  {report.stats.mostActiveDayCommits}
                </p>
                <p className="text-xs text-muted-foreground">Peak Day</p>
              </div>
            </motion.div>

            {/* Activity Chart */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.2 }}
              className="rounded-xl border border-border/50 bg-card/30 p-6"
            >
              <h2 className="mb-4 text-lg font-semibold">Daily Activity</h2>
              <ActivityChart data={report.stats.commitsByDay} />
            </motion.div>

            {/* Detailed Breakdown - Individual commit summaries */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.3 }}
            >
              <h2 className="mb-4 text-lg font-semibold">Work Breakdown</h2>
              <div className="space-y-4">
                {report.detailedBreakdown.map((breakdown, index) => (
                  <motion.div
                    key={breakdown.repo}
                    initial={{ opacity: 0, y: 10 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: 0.3 + index * 0.05 }}
                    className="rounded-xl border border-border/50 bg-card/30 p-5"
                  >
                    <div className="mb-3 flex items-center justify-between">
                      <div className="flex items-center gap-3">
                        <span className="font-mono text-sm font-semibold">
                          {breakdown.repo}
                        </span>
                        <span className="rounded-full bg-accent/10 px-2 py-0.5 text-xs font-medium text-accent">
                          {breakdown.commitCount} commits
                        </span>
                      </div>
                      <a
                        href={breakdown.repoUrl}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-xs text-muted-foreground hover:text-accent hover:underline"
                      >
                        View on GitHub →
                      </a>
                    </div>

                    <p className="mb-3 text-sm text-muted-foreground">
                      {breakdown.summary}
                    </p>

                    {breakdown.highlights.length > 0 && (
                      <ul className="space-y-1.5">
                        {breakdown.highlights.map((highlight, i) => (
                          <li key={i} className="flex gap-2 text-sm">
                            <span className="text-green-500">✓</span>
                            <span>{highlight}</span>
                          </li>
                        ))}
                      </ul>
                    )}
                  </motion.div>
                ))}
              </div>
            </motion.div>
          </motion.div>
        ) : null}
      </AnimatePresence>
    </div>
  )
}
