name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  verify:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run verification tests
      run: npm run verify

    - name: Check build size and performance
      run: |
        npm run build
        echo "Build completed successfully"
        
        # Check build output
        if [ -d ".next" ]; then
          echo "✅ Build artifacts created"
          du -sh .next/
        else
          echo "❌ Build artifacts not found"
          exit 1
        fi

  lint-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run ESLint
      run: npm run lint

    - name: Run TypeScript check
      run: npm run type-check

    - name: Check formatting
      run: npm run format:check

  build-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build for production
      run: NODE_ENV=production npm run build

    - name: Test build artifacts
      run: |
        # Check if critical files exist
        test -f .next/BUILD_ID || exit 1
        test -d .next/static || exit 1
        echo "✅ All build artifacts present" 